// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: comments.sql

package database

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments (user_id, content)
VALUES ($1, $2)
RETURNING id, user_id, content, created_at, (SELECT email FROM users WHERE id = $1)
`

type CreateCommentParams struct {
	UserID  uuid.NullUUID
	Content string
}

type CreateCommentRow struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Content   string
	CreatedAt sql.NullTime
	Email     string
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error) {
	row := q.db.QueryRowContext(ctx, createComment, arg.UserID, arg.Content)
	var i CreateCommentRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Content,
		&i.CreatedAt,
		&i.Email,
	)
	return i, err
}

const listComments = `-- name: ListComments :many
SELECT c.id, c.user_id, c.content, c.created_at, u.email
FROM comments c
JOIN users u ON c.user_id = u.id
ORDER BY c.created_at DESC
`

type ListCommentsRow struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Content   string
	CreatedAt sql.NullTime
	Email     string
}

func (q *Queries) ListComments(ctx context.Context) ([]ListCommentsRow, error) {
	rows, err := q.db.QueryContext(ctx, listComments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentsRow
	for rows.Next() {
		var i ListCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Email,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
