// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"

	"github.com/google/uuid"
)

type Comment struct {
	ID        uuid.UUID
	UserID    uuid.NullUUID
	Content   string
	CreatedAt sql.NullTime
}

type User struct {
	ID        uuid.UUID
	Email     string
	Password  string
	CreatedAt sql.NullTime
}
